version: '3.4'

services:
  webapplication-estudos-asp-net-core-rabbitmq.v1:
    image: ${DOCKER_REGISTRY-}webapplicationestudosaspnetcorerabbitmqv1
    build:
      context: .
      dockerfile: webapplication-estudos-asp-net-core-rabbitmq.v1/Dockerfile
    depends_on:
      - rabbitmqcompose
  rabbitmqcompose: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmqcompose"
    labels:
      NAME: "rabbitmqcompose"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
